const ActionTypes = {
  SIGNIN_DIALOG_OPEN: 'SIGNIN_DIALOG_OPEN',
  SIGNIN_DIALOG_CLOSE: 'SIGNIN_DIALOG_CLOSE',
  SIGNIN_DIALOG_EMAIL_CHANGE: 'SIGNIN_DIALOG_EMAIL_CHANGE',
  SIGNIN_DIALOG_PASSWORD_CHANGE: 'SIGNIN_DIALOG_PASSWORD_CHANGE',
  SIGNIN_DIALOG_SIGNIN_START: 'SIGNIN_DIALOG_SIGNIN_START'
}

export default ActionTypes
