const ActionTypes = {
  CREATE_ACCOUNT_CANCEL: 'CREATE_ACCOUNT_CANCEL',
  CREATE_ACCOUNT_CHANGE: 'CREATE_ACCOUNT_CHANGE',
  CREATE_ACCOUNT_OPEN: 'CREATE_ACCOUNT_OPEN',
  CREATE_ACCOUNT_SUBMIT: 'CREATE_ACCOUNT_SUBMIT',
  PREFERENCES_DRAWER_OPEN: 'PREFERENCES_DRAWER_OPEN',
  PREFERENCES_DRAWER_CLOSE: 'PREFERENCES_DRAWER_CLOSE',
  PREFERENCES_CHANGE: 'PREFERENCES_CHANGE',
  SIGNIN_DIALOG_OPEN: 'SIGNIN_DIALOG_OPEN',
  SIGNIN_DIALOG_CANCEL: 'SIGNIN_DIALOG_CANCEL',
  SIGNIN_DIALOG_EMAIL_CHANGE: 'SIGNIN_DIALOG_EMAIL_CHANGE',
  SIGNIN_DIALOG_PASSWORD_CHANGE: 'SIGNIN_DIALOG_PASSWORD_CHANGE',
  SIGNIN_DIALOG_SIGNIN_START: 'SIGNIN_DIALOG_SIGNIN_START',
  SIGNIN_DIALOG_SIGNIN_SUCCESS: 'SIGNIN_DIALOG_SIGNIN_SUCCESS',
  SIGNOUT: 'SIGNOUT'
}

export default ActionTypes
